name: Stream M3U8 Generator

on:
  workflow_dispatch:    # Manuell auslösbar
  push:                 # Bei jedem Push ins Repository
    branches:
      - main            # Passe ggf. den Branchnamen an

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Oder deine gewünschte Version

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Run script
        run: python test.py  # Passe den Dateinamen an

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: m3u8-output
          path: streams.m3u8
