name: YouTube Stream Checker

on:
  workflow_dispatch: # Manuell ausführbar im GitHub UI
  schedule:
    - cron: '0 * * * *'  # Optional: führt das Skript stündlich aus

jobs:
  check-streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run YouTube Stream Checker
        run: python check_streams.py
